spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: # enter sql user
    password: # enter sql password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;database=RestaurantOnline

  jpa:
    database: sql_server
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  security:
    user:
      name: user
      password: password
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000




















    #spring.datasource.url=jdbc:sqlserver://${POSTGRES_HOST:DESKTOP-IDFPJR7};${POSTGRES_DB:database=RestaurantOnline}
    #spring.datasource.username=${POSTGRES_USER:sa}
    #spring.datasource.password=${POSTGRES_PASSWORD:12as12as}
    #spring.datasource.driver-class-name=${POSTGRES_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}
    #spring.jpa.database-platform=${POSTGRES_DIA:org.hibernate.dialect.SQLServerDialect}
    #



    ##docker run -p 8080:8080 --name order_online --net order_online_network -e POSTGRES_HOST=DESKTOP-IDFPJR7 -e POSTGRES_DB=RestaurantOnline -e POSTGRES_USER=sa -e POSTGRES_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver -e POSTGRES_DIA=org.hibernate.dialect.SQLServerDialect -e POSTGRES_PASSWORD=12as12as -e POSTGRES_PORT=1433 order_online

