spring:
  datasource:
    username: sa
    password: 12as12as
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://DESKTOP-IDFPJR7;database=RestaurantOnline

  jpa:
    database: sql_server
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  security:
    user:
      name: ali
      password: 12as12as
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000